/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName DEMOGAME_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(SampleEvent)

#ifndef NAMES_ONLY


struct SampleClass_eventSampleEvent_Parms
{
    INT I;
};
class ASampleClass : public AActor
{
public:
    INT MyInteger;
    FStringNoInit MyString;
    BITFIELD MyBool:1 GCC_PACK(PROPERTY_ALIGNMENT);
    FVector MyVector GCC_PACK(PROPERTY_ALIGNMENT);
    DECLARE_FUNCTION(execSampleNativeFunction);
    void eventSampleEvent(INT I)
    {
        SampleClass_eventSampleEvent_Parms Parms;
        Parms.I=I;
        ProcessEvent(FindFunctionChecked(DEMOGAME_SampleEvent),&Parms);
    }
    DECLARE_CLASS(ASampleClass,AActor,0|CLASS_Config,DemoGame)
    NO_DEFAULT_CONSTRUCTOR(ASampleClass)
};

#endif

AUTOGENERATE_FUNCTION(ASampleClass,-1,execSampleNativeFunction);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DEMOGAME_NATIVE_DEFS
#define DEMOGAME_NATIVE_DEFS

DECLARE_NATIVE_TYPE(DemoGame,ASampleClass);

#define AUTO_INITIALIZE_REGISTRANTS_DEMOGAME \
	ASampleClass::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindDemoGameASampleClassNative; \

#endif // DEMOGAME_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(ASampleClass) GDemoGameASampleClassNatives[] = 
{ 
	MAP_NATIVE(ASampleClass,execSampleNativeFunction)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(DemoGame,ASampleClass);

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ASampleClass)
#endif // VERIFY_CLASS_SIZES
